name: Preview # ì›Œí¬í”Œë¡œìš° ì´ë¦„

on:
  pull_request: # íŠ¹ì • ì´ë²¤íŠ¸ ë°œìƒ ì‹œ ì‹¤í–‰
    branches: ['main', 'dev'] # mainê³¼ dev ë¸Œëœì¹˜ì—ì„œ PR ìƒì„± ì‹œ ì‹¤í–‰

permissions: # GitHub Actionsì˜ ê¶Œí•œ ì„¤ì •
  contents: write # ì½˜í…ì¸ ë¥¼ ì½ê³  ì“°ëŠ” ê¶Œí•œ
  pages: write # GitHub Pages ë°°í¬ ê¶Œí•œ
  deployments: write # ë°°í¬ ê¶Œí•œ
  id-token: write # OIDC í† í° ìƒì„± ê¶Œí•œ
  issues: write # ì´ìŠˆ ìƒì„± ë° í¸ì§‘ ê¶Œí•œ
  pull-requests: write # PR ìƒì„± ë° í¸ì§‘ ê¶Œí•œ

jobs:
  storybook-preview:
    runs-on: ubuntu-20.04 # ì›Œí¬í”Œë¡œìš° ì‹¤í–‰ í™˜ê²½ (Ubuntu 20.04)

    env:
      CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
    steps:
      - name: ì €ì¥ì†Œ ì²´í¬ì•„ì›ƒ
        uses: actions/checkout@v3 # GitHub Actionsì˜ ê³µì‹ ì²´í¬ì•„ì›ƒ ì•¡ì…˜
        with:
          fetch-depth: 0 # ì „ì²´ Git ê¸°ë¡ì„ ê°€ì ¸ì˜´ (CI ìµœì í™”ë¥¼ ìœ„í•´ ê¸°ë³¸ê°’ì€ 1)

      - name: ìºì‹œ ì¢…ì†ì„±
        id: cache
        uses: actions/cache@v3 # ìºì‹œë¥¼ ì‚¬ìš©í•˜ì—¬ ë¹Œë“œ ì†ë„ ê°œì„ 
        with:
          path: '**/node_modules' # ìºì‹œ ëŒ€ìƒ ê²½ë¡œ
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}-storybook # ìºì‹œ í‚¤ ì„¤ì •

      - name: ì¢…ì†ì„± ì„¤ì¹˜
        if: steps.cache.outputs.cache-hit != 'true' # ìºì‹œê°€ ì—†ì„ ë•Œë§Œ ì‹¤í–‰
        run: yarn install # Yarnìœ¼ë¡œ í”„ë¡œì íŠ¸ ì˜ì¡´ì„± ì„¤ì¹˜

      - name: Chromaticì— ê²Œì‹œ
        id: chromatic
        uses: chromaui/action@latest
        with:
          onlyChanged: true # ë³€ê²½ëœ ìŠ¤í† ë¦¬ë§Œ ì—…ë¡œë“œ
          autoAcceptChanges: true # Chromaticì—ì„œ ë³€ê²½ ì‚¬í•­ ìë™ ìŠ¹ì¸
          debug: true

      - name: í˜„ì¬ ì‹œê°„ ê°€ì ¸ì˜¤ê¸°
        uses: josStorer/get-current-time@v2 # í˜„ì¬ ì‹œê°„ ê°€ì ¸ì˜¤ëŠ” ì•¡ì…˜
        id: current-time
        with:
          format: 'YYYYë…„ MMì›” DDì¼ HHì‹œ mmë¶„ ssì´ˆ' # ì‹œê°„ í˜•ì‹
          utcOffset: '+09:00' # í•œêµ­ ì‹œê°„ëŒ€ë¡œ ì„¤ì • (UTC+9)

    outputs: # ë‹¤ìŒ Jobì—ì„œ ì‚¬ìš©í•  ì¶œë ¥ê°’ ì„¤ì •
      storybook_url: ${{ steps.chromatic.outputs.storybookUrl }} # Chromatic URL
      currnent_time: ${{ steps.current-time.outputs.formattedTime }} # í¬ë§·ëœ í˜„ì¬ ì‹œê°„

  github-bot-storybook:
    runs-on: ubuntu-latest # ìµœì‹  Ubuntu í™˜ê²½
    needs: [storybook-preview] # `storybook-preview` Jobì´ ì™„ë£Œëœ í›„ ì‹¤í–‰

    steps:
      - name: PR ì½”ë©˜íŠ¸ ë‚¨ê¸°ê¸°
        uses: thollander/actions-comment-pull-request@v2 # PRì— ëŒ“ê¸€ ë‚¨ê¸°ëŠ” ì•¡ì…˜
        with:
          comment_tag: ${{github.event.number}}-storybook # ëŒ“ê¸€ íƒœê·¸ë¡œ ì¤‘ë³µ ë°©ì§€
          message: |
            ğŸ’„ Storybook: ${{ needs.storybook-preview.outputs.storybook_url }} # Chromaticì—ì„œ ìƒì„±ëœ Storybook URL
            ğŸ•– Update: ${{ needs.storybook-preview.outputs.currnent_time }} # í˜„ì¬ ì‹œê°„
